# Generated by Django 3.1.3 on 2022-11-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('is_used', models.BooleanField(default=True, help_text='中古ならTrue')),
                ('votes', models.IntegerField(default=0)),
                ('answer', models.CharField(max_length=300)),
                ('ans1', models.CharField(max_length=300)),
                ('ans2', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Cloth2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('is_used', models.BooleanField(default=True, help_text='中古ならTrue')),
                ('votes', models.IntegerField(default=0)),
                ('answer', models.CharField(max_length=300)),
                ('ans1', models.CharField(max_length=300)),
                ('ans2', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Cloth3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('is_used', models.BooleanField(default=True, help_text='中古ならTrue')),
                ('votes', models.IntegerField(default=0)),
                ('answer', models.CharField(max_length=300)),
                ('ans1', models.CharField(max_length=300)),
                ('ans2', models.CharField(max_length=300)),
                ('images', models.ImageField(upload_to='')),
            ],
        ),
    ]
